SELECT 

fuente, 
'CUR' as whs_code,
item_code, 
total_cd, 
dev_multivende + dev_shopify as dev_multivende, 
dev_canal_directo, 
dev_mayorista, 
dev_dafiti, 
dev_falabella, 
dev_argentina, 
dev_peru, 
dev_falabella_colombia, 
dev_leonisa, 
dev_falabella_market,
GREATEST(0, res_argentina - dev_argentina) as res_argentina,
GREATEST(0, res_siman_peru ) as res_siman_peru,
GREATEST(0, res_falabella - dev_falabella) as res_falabella,
GREATEST(0, res_falabella_colombia - dev_falabella_colombia) as res_falabella_colombia,
GREATEST(0, res_mayorista - dev_mayorista) as res_mayorista,
GREATEST(0, res_multivende - dev_multivende) + GREATEST(0, res_shopify - dev_shopify) as res_multivende,
GREATEST(0, res_peru - dev_peru) as res_peru,
GREATEST(0, res_ripley) as res_ripley,
GREATEST(0, res_paris) as res_paris,
GREATEST(0, res_tienda) as res_tienda,
GREATEST(0, res_alianza) as res_alianza,
GREATEST(0, res_especial) as res_especial,
GREATEST(0, res_dafiti - dev_dafiti) as res_dafiti,
GREATEST(0, res_importaciones) as res_importaciones,
GREATEST(0, res_leonisa - dev_leonisa) as res_leonisa,
fecha_actualizacion as fecha_actualizacion_origen

FROM origen.hechos_stock_sap_reservas